import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import api from "../api/axios";
import { useAuth } from "../context/AuthContext";

const money = (v) => new Intl.NumberFormat("en-KE", { style: "currency", currency: "KES", maximumFractionDigits: 0 }).format(Number(v) || 0);
export default function SellerDashboardPro() {
  const { user } = useAuth(); const [books,setBooks]=useState([]); const [orders,setOrders]=useState([]); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  useEffect(()=>{let active=true; Promise.all([api.get("/seller/books"),api.get("/seller/orders")]).then(([b,o])=>{if(active){setBooks(Array.isArray(b.data)?b.data:b.data?.books||[]);setOrders(Array.isArray(o.data)?o.data:o.data?.orders||[]);}}).catch(e=>active&&setError(e.response?.data?.message||"Unable to load seller dashboard.")).finally(()=>active&&setLoading(false));return()=>{active=false}},[]);
  const stats=useMemo(()=>({listings:books.length,approved:books.filter(b=>b.status==="approved").length,pending:books.filter(b=>b.status==="pending").length,revenue:orders.filter(o=>String(o.paymentStatus).toLowerCase()==="paid").reduce((s,o)=>s+Number(o.books?.filter(i=>String(i.seller?._id||i.seller)===String(user?._id)).reduce((x,i)=>x+Number(i.price||0)*Number(i.quantity||1),0)||0),0)}),[books,orders,user]);
  return <main className="min-h-[75vh] bg-slate-50 dark:bg-slate-950"><div className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><div className="rounded-3xl bg-gradient-to-br from-emerald-950 to-slate-900 p-6 text-white shadow-xl sm:p-8"><p className="text-sm font-bold text-emerald-300">Seller workspace</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">Welcome, {user?.name||"Seller"}</h1><p className="mt-2 text-slate-300">Manage your catalogue, monitor orders and grow your BookHub business.</p><div className="mt-6 flex flex-wrap gap-3"><Link to="/seller/add-book" className="rounded-xl bg-emerald-600 px-5 py-3 font-bold hover:bg-emerald-500">Add a book</Link><Link to="/seller/books" className="rounded-xl border border-white/20 px-5 py-3 font-bold hover:bg-white/10">Manage catalogue</Link></div></div>{error&&<p className="mt-4 rounded-xl bg-red-50 p-4 text-red-700">{error}</p>}{loading?<p className="mt-8 text-slate-500">Loading dashboard…</p>:<><section className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Listings",stats.listings],["Approved",stats.approved],["Pending review",stats.pending],["Sales value",money(stats.revenue)]].map(([l,v])=><div key={l} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><p className="text-sm font-semibold text-slate-500">{l}</p><p className="mt-2 text-2xl font-black dark:text-white">{v}</p></div>)}</section><section className="mt-6 grid gap-6 lg:grid-cols-2"><div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 className="text-xl font-black dark:text-white">Catalogue health</h2><div className="mt-5 space-y-3"><p className="flex justify-between"><span>Approved listings</span><b>{stats.approved}</b></p><p className="flex justify-between"><span>Awaiting review</span><b>{stats.pending}</b></p><p className="flex justify-between"><span>Total listings</span><b>{stats.listings}</b></p></div></div><div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 className="text-xl font-black dark:text-white">Recent sales</h2>{orders.length===0?<p className="mt-4 text-slate-500">No sales yet.</p>:orders.slice(0,5).map(o=><div key={o._id} className="mt-4 flex justify-between border-b border-slate-100 pb-3 dark:border-slate-800"><span className="font-semibold">#{String(o._id).slice(-6)}</span><span className="font-bold">{o.paymentStatus}</span></div>)}</div></section></>}</div></main>;
}
